### ISSUE TITLE
Broken links in https://docs.pixelfed.org/ probably due to config.toml issues

### ISSUE THREAD

**Issue by ambiamber** [pixelfed/docs#102]
Description of issue:

I was browsing the documentation on https://docs.pixelfed.org/ and found broken links.  When I looked at the markdown versions in this repo the links work.

Example:

This page: https://docs.pixelfed.org/technical-documentation/config/  has a link to this page:
https://docs.pixelfed.org/technical-documentation/running-pixelfed/installation.md#configure-environment-variables

```text
For a user-facing guide to which environment variables you might want to set, check out the <a href=../running-pixelfed/installation.md#configure-environment-variables>installation guide</a> instead.
```

In this repo I do not get a 404 viewing that content:

https://github.com/pixelfed/docs/blob/main/content/en/technical-documentation/config.md

```
For a user-facing guide to which environment variables you might want to set, check out the [installation guide](https://github.com/pixelfed/docs/blob/main/content/en/running-pixelfed/installation.md#configure-environment-variables) instead. {{}}
```

**Comment by trwnh** [comment]
oh, this would probably be an artifact of migrating from vuepress (which automatically translates .md links to html links) to hugo (which does not do that automatically by default)

- option 1: convert all such links to point toward the URI
- option 2: setup something like markdown render hooks to render relative markdown links: https://discourse.gohugo.io/t/relative-markdown-links-markdown-render-hooks/22674

**Comment by trwnh** [comment]
solved with https://github.com/bep/portable-hugo-links/blob/master/layouts/_default/_markup/render-link.html

**Comment by trwnh** [comment]
Fixed inhttps://github.com/pixelfed/docs/commit/b2c68f423ad90771e603eb50ca3df8374a01a225
