### ISSUE TITLE
how-to setup email variables is not documented? or outdate link

### ISSUE THREAD

**Issue by albjeremias** [pixelfed/docs#39]
Can you please fix:
https://docs.pixelfed.org/installing-pixelfed/installation.html#email-variables

here it is: 
https://github.com/pixelfed/docs/blob/a477b6527e81d237749d886d16a3ed3abd22e631/installing-pixelfed/installation.md#email-variables

How do I send an email using an stmp server? or how do I confirm  my account if i don't have email enabled?

**Comment by dansup** [comment]
@albjeremias Please refer to the [Configuring Mail](https://docs.pixelfed.org/installing-pixelfed/configuring-mail.html) section of the documentation!
