### ISSUE TITLE
Arch Linux: php-fpm.service prevents installation into /home/pixelfed

### ISSUE THREAD

**Issue by user171** [pixelfed/docs#43]
After following the instructions for installation on Arch (https://docs.pixelfed.org/installing-pixelfed/guides/arch.html) when loading the pixelfed home page in the browser (Firefox / Chromium) I get the `File not found.` message.

I have set up the `nginx.conf` as per the docs, only changing my `server_name` to what I type in the browser.
I have checked the rest of the configuration, it looks good. I have checked the content of `$document_root$fastcgi_script_name` and it returns precisely the path where the `public` folder is.

Any idea what could have gone wrong or how I can find out?

**Comment by trwnh** [comment]
Will be fixed in next commits; Arch guide will now use `/usr/share/webapps` in keeping with Arch guidelines on how to package webapps.
