### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by 736b** [pixelfed/docs#54]
I'm most likely just stupid and not following the manual correctly, but in the process of installing, you say to run the following commands:
composer install
update .env file
I got the first command by doing `apt install composer` on a Debian server, but the "update" command I can't find and don't know from my 15 years of Linux knowledge. Would it be possible, to update the manual and just add the commands you need to install the prerequisites on some common distros?

**Comment by trwnh** [comment]
it looks like that line is intended to be a comment. it does appear confusingly to suggest running some mysterious "update" command as root, yes... this is not what the intention is.

for what it's worth, the documentation used to be much more detailed regarding installation -- here's a link to the old installation guide https://github.com/pixelfed/docs/tree/328ead9822229432433c2635939659dfaddeab20/installing-pixelfed

**Comment by 736b** [comment]
Alright, I got it now, thanks to your clarification.

**Comment by trwnh** [comment]
Will be made clearer in next commits
