### ISSUE TITLE
https://docs.pixelfed.org/installing-pixelfed/ 404

### ISSUE THREAD

**Issue by ImaCrea** [pixelfed/docs#55]
Hey,
be careful there's a 404 on the "Install Pixelfed" link in the footer of https://pixelfed.org/

**Comment by trwnh** [comment]
`/installing-pixelfed` has changed to `/running-pixelfed`

**Comment by trwnh** [comment]
@dansup pixelfed.org needs a redeploy https://github.com/pixelfedLabs/delta/commit/98ccb7d02272c8b7eaf7a906ae1fa63fc3e3dd40
