### ISSUE TITLE
How to use the diagnosis code?

### ISSUE THREAD

**Issue by songsammy** [pixelfed/docs#77]
I've encountered something went wrong several times.  
Copy diagnosis details, and I got a base 64 encoded string. Upon decoding the base64, I got a JSON containing `iv`,`value` and `mac`, Can you add instructions on how toake use of them?

**Comment by dansup** [comment]
## Decode diagnosis payload via web
1. Navigate to your admin dashboard
2. Click on **Diagnostics** tab
3. Paste payload into textarea that says `Enter payload here`
4. Click **Decrypt** button

----

## Decode diagnosis payload via CLI
1. Run `php artisan tinker`
2. type `decrypt('payload here')` and replace **payload here** with your payload
3. Hit enter

**Comment by songsammy** [comment]
Thanks. Maybe you should put this on https://docs.pixelfed.org/running-pixelfed/troubleshooting.html
