### ISSUE TITLE
Is there any way to disable photo compression?

### ISSUE THREAD

**Issue by DarkVessel** [pixelfed/docs#93]
I want to deploy this project on my server and publish photos there without any compression.
I tried to find information about this in the documentation, but I didn't find anything. Thank you in advance for any help.

**Comment by DarkVessel** [comment]
I found some config, but I'm not sure that it can be touched.
https://github.com/pixelfed/pixelfed/blob/dev/config/image-optimizer.php

**Comment by trwnh** [comment]
You can use the environment variable `PF_OPTIMIZE_IMAGES` and set it to false. One caveat currently is that thumbnails don't get generated when you set this variable, as thumbnail generation is currently tied to the image optimizer. This is being worked on!

https://docs.pixelfed.org/technical-documentation/config/#pf_optimize_images
